# Generated by Django 4.2.5 on 2023-10-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puser',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
